package pp2014.team32.shared.enums;

/**

 *
* @author Brokmeier, Pascal
 * @version 25.05.14
 */
public enum MessageType {
	ATTRIBUTECHANGEINFO,
	ATTRIBUTEUPGRADEREQUEST,
	AUTHENTICATIONRESPONSE,
	BULKMESSAGEPACKAGE,
	BULLETADDITION,
	CHARACTERDEADINFO,
	CHATMESSAGE,
	CRAFTINGREQUEST,
	DRAWABLEOBJECTADDITION,
	FIXEDOBJECTREMOVAL,
	HEALTHUPDATE,
	INVENTORYACTIONREQUEST,
	INVENTORYUPDATE,
	LEVELDATA,
	LEVELUPGRADE,
	LOGOFFMESSAGE,
	MOVABLEOBJECTREMOVAL,
	MOVEMENTINFO,
	MOVEMENTREQUEST,
	NEWLEVELDATAREQUEST,
	PING,
	REGISTRATIONREQUEST,
	RESPAWNREQUEST,
	TORCHMESSAGE,
    UNCOVERMESSAGE,
    USERAUTHENTICATION;
}
